### ISSUE TITLE
Actuele zoekresultaten worden niet gesorteerd

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/API-Kennisbank#105]
De API standaard schrijft niet voor hoe zoekresultaten in de API moeten worden gesorteerd. Wanneer de client behoefte heeft aan gesorteerde resultaten, moet zij de ontvangen resultaten zelf sorteren. Dit betekent dat er in de berichtspecificaties geen gebruik gemaakt wordt van de 'sorteer' parameter.

**Comment by melsk-r** [comment]
JBo: Niet overnemen
HK:
RM: Niet overnemen
MV: Niet overnemen
GJ: Niet overnemen
JBi: Geen mening

JBo : Dit is een projectkeuze
MV: Eens
RM: Eens met JBo
GJ: +1 JBo; een sorteer parameter kan overigens best een nuttige functie hebben.

**Comment by JohanBoer** [comment]
Henri, zou jij aan deze jouw meneing willen toevoegen. Mocht die overeenstemmen met de rest dan kan deze van de lijst af.

**Comment by HenriKorver** [comment]
HK: Niet overnemen

**Comment by melsk-r** [comment]
Dit voorstel wordt door niemand gesteund en wordt daarmee afgevoerd.
Ik sluit dit issue.
