### ISSUE TITLE
Er komt een aparte besluitenregistratie

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/API-Kennisbank#107]
Er komt een aparte besluitenregistratie (naast ZRC, ZTC en DRC) om besluiten in vast te leggen. De motivatie hiervoor is dat besluiten een bestaansrecht hebben onafhankelijk van zaken: niet elk besluit ontstaat gedurende de uitvoering van een zaak (denk aan raadsbesluiten).

Hierbij lopen we wat vooruit, maar volgen we wel data-bij-de-bron principes uit Common Ground. BESLUITTYPE laten we vooralsnog in de ZTC. Nader bepaald moet gaan worden hoe we hiermee omgaan, zoals onderbrengen in de BRC, aparte type-componenten cq. api’s e.d.

Dit betekent dat er voor BESLUIT een informatiemodel moet komen, onttrokken aan het RGBZ. BESLUIT krijgt een optionele relatie naar ZAAK.

De verwachting is dat er later vergelijkbare designkeuzes gemaakt worden voor andere resources, zoals bijvoorbeeld klantcontacten.

**Comment by melsk-r** [comment]
JBo: Niet overnemen
HK:
RM: Niet overnemen
MV: Niet overnemen
GJ: Niet overnemen
JBi: Niet overnemen

MV: Dit is een project-specifieke design rule en eigenlijk zelfs dat niet.
RM: Valt hieruit wel een generieke DD te destilleren? Voortschrijdend inzicht leert mij dat het hier geen Design Rule betrfeft. Het zegt nl. niets over de inhoud van de API standaard maar is een besluit om tot een nieuwe API standaard te komen.
JBi: Lijkt op een beslissing rond inrichting van gegevens en niet zo zeer een algemene regel over API's.

**Comment by JohanBoer** [comment]
Deze beslissing hoort thuis in ons het intake-proces van een voorstel. We kunnen deze met een gerust hart sluiten.
