### ISSUE TITLE
Naamgeving van enumeratiewaarden wordt ontdaan van spaties en bijzondere tekens

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/API-Kennisbank#111]
Er wordt naar gestreefd om enumeratiewaarden te ontdoen van spaties en bijzondere tekens. Indien mogelijk worden spaties in enumeratiewaarden vervangen door underscores.

**Comment by melsk-r** [comment]
JBo: Overnemen
HK: Laten vervallen
RM: Laten vervallen
MV: laten vervallen
GJ: Niet overnemen / laten vervallen
JBi: Kopie dus laten vervallen

JBo: Kopie van [DD2.4](https://github.com/VNG-Realisatie/API-Kennisbank/tree/master/Design%20rules)
RM: Is inderdaad een kopie. Heeft weinig nut om deze DD dan op te nemen.
GJ: [DD2.4](https://github.com/VNG-Realisatie/API-Kennisbank/tree/master/Design%20rules) lost dit al op

**Comment by JohanBoer** [comment]
Om dat er een kopie van deze issue is kan deze vervallen. Dat ben ik met de meerderheid eens.
