### ISSUE TITLE
Te hanteren methode bij Zaak afsluiten

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/API-Kennisbank#112]
Een zaak wordt afgesloten door een eindstatus toe te kennen aan een ZAAK. Elk ZAAKTYPE heeft minimaal één STATUSTYPE. De eindstatus binnen een ZAAKTYPE is het STATUSTYPE met het hoogste volgnummer.

Het toekennen van dit STATUSTYPE aan een ZAAK bepaalt ook een logisch af te leiden ZAAK.einddatum; dit is namelijk de datum waarop de eindstatus is toegekend. Om die reden is ZAAK.einddatum een alleen-lezen attribuut van ZAAK.

Als een ZAAK een eindstatus heeft dan is de zaak afgesloten en mogen gegevens van de zaak niet meer aangepast worden (behalve om redenen van correctie). Dit is voorlopig een verantwoordelijkheid van de consumer en/of autorisatielaag.

In API-calls, kan de flow er als volgt uit zien:

Consumer wil onderstaande ZAAK afsluiten:

```
GET /zrc/api/v1/zaken/12345

HTTP 200
{
    "einddatum": null,
    // ...
}
```

Consumer wil onderstaande eindstatus zetten:

```
GET /ztc/api/v1/catalogus/12345/statustypen?zaaktype=/ztc/api/v1/zaaktype/44912

HTTP 200
[{
    "uuid": 99321,
    "volgnummer": 1,
    "isEindstatus": false,
    // ...
},{
    "uuid": 67890,
    "volgnummer": 2,  # Het laatste STATUSTYPE binnen dit ZAAKTYPE
    "isEindstatus": true,
    // ...
}]
```

Consumer werkt een ZAAK bij met de eindstatus:

```
POST /zrc/api/v1/zaakstatussen
{
    "zaak": "/zrc/api/v1/zaken/45678",
    "statustype": "/ztc/api/v1/catalogus/12345/statustypen/67890",
    "datumStatusGezet": "2018-10-08T12:23:07+01:00",
    // ...
}
```

Consumer haalt de ZAAK opnieuw op:

```
GET /zrc/api/v1/zaken/12345

HTTP 200
{
    "einddatum": "2018-10-08",
    // ...
}
```

**Ratio**: In de ZDS 1.x standaard is er nog geen eenduidig besluit genomen over hoe een zaak wordt afgesloten: Dit kan door het toevoegen van de laatste status (STATUSTYPE met het hoogste volgnummer) aan de ZAAK of door het vullen van de einddatum (van de ZAAK).

Er is echter behoefte aan een consistente manier om zaken af te sluiten. In deze oplossing worden zowel ZAAK.einddatum als STATUSTYPE gebruikt waarbij er geen onduidelijkheid meer ontstaat over hoe een ZAAK wordt afgesloten.

**Comment by melsk-r** [comment]
JBo:  Niet overnemen
HK:
RM: Niet overnemen
MV: Niet overnemen
GJ: Niet overnemen
JBi: Niet overnemen

MV: is alleen van toepassing op ZGW API's
RM: is geen algemeen toepasbare Design Rule maar meer een beslissing m.b.t. het te doorlopen proces.

**Comment by JohanBoer** [comment]
Henri, de rest van het team denkt hier hetzelfde over. Wil jij jouw mening toevoegen ? Mogelijk kan deze dan worden afgevoerd.

**Comment by HenriKorver** [comment]
HK: Niet overnemen (te domeinspecifiek)

**Comment by melsk-r** [comment]
Het voorstel wordt door niemand ondersteund en wordt daarmee afgevoerd.
Ik sluit het issue.
