### ISSUE TITLE
Documenteren serialisatie-varianten van relatie-klassen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#121]
- Variant Zaakgericht werken ( bv documenten / zaakinformatieobjecten ) 
- Variant ORI-oud ( Relatieklasse als zelfstandige resource ) 
- Variant IMWOZ ( Relatieklasse opnemen als groep bij de basisresource met verwijzing naar gerelateerde resource )

**Comment by melsk-r** [comment]
Hiervoor is een issue in de MDD repo opgevoerd (https://github.com/VNG-Realisatie/Model-Driven-Design/issues/34)
