### ISSUE TITLE
API Design rules 404

### ISSUE THREAD

**Issue by sgort** [VNG-Realisatie/API-Kennisbank#141]
Op https://vng-realisatie.github.io/API-Kennisbank/Design%20rules/inhoud geven 3, 4, 5 én 6 een 404 pagina.

**Comment by melsk-r** [comment]
@sgort Links geven nu geen 404 pagina meer. De pagina's die achter de links zitten zijn echter nog leeg.
[Hier](https://github.com/VNG-Realisatie/API-Kennisbank/blob/master/Design%20rules/readme.md) vind je de Design rules waarvan het de bedoeling is dat deze mettertijd ook op de GitHub Pages pagina's zullen verschijnen.
