### ISSUE TITLE
Vertaling van relaties 0-n of 1-n

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#35]
Een 0-op-N of 1-op-N relatie tussen objecttypen A en B in een informatiemodel zoals RGBZ of ImZTC kan eenvoudig vertaald worden naar een REST API door een hyperlink op te nemen in de resource dat meerdere keren kan voorkomen in de relatie, B in dit geval. Het veld met de hyperlink in resource B verwijst naar de gerelateerde resource A. 

Dit is het principe van ‘linked data’.      

Bijvoorbeeld in het RGBZ kan een zaak kan nul of meer statussen hebben en een status kan niet bestaan zonder een zaak, oftewel er is sprake van een 1-op-N relatie tussen Zaak en Status. De resource Status bevat naast zijn eigen gegevens het (toegevoegde) veld "zaak" dat de url naar de resource van de gerelateerde zaak bevat.      

Opmerking: We gaan er gemakshalve vanuit dat 0-op-N of 1-op-N relaties geen eigen gegevens hebben. In het RGBZ komt dit in ieder geval niet voor.

**Comment by JohanBoer** [comment]
Oorsprong : https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/ontwerpkeuzes

Johan: Bespreken
Henri: Discussie
Robert: Overnemen
Michiel: Overnemen
Gershon: Bespreken
Jeanot: Toelichting gewenst

Robert: De laatste zin van de eerste alinea van de toelichting zorgt voor verwarring vind ik. Wat wordt bedoelt. Verder zou ik het deel van de toelichting dat gaat over N-op-M in een andere DD plaatsen of toevoegen met de volgende DD

Henri: Zie hier (https://github.com/HenriKorver/KP-APIs/blob/master/API-strategie-extensies/ext-many-to-many-relations.md) voor een simpelere uitleg van deze design rule. Deze design rule probeer ik nu in te dienen bij de Landelijke API Strategie.

Jeanot: Zou dit graag even met een voorbeeldje zien. Bij lezen lijkt het of er aan het begin iets anders staan dan aan het einde. Dus ik begrijp het nog niet 100%.

**Comment by JohanBoer** [comment]
Afspraak overleg dd 19-02-2021 : Henri werkt een voorbeeld uit ter toelichting.

**Comment by JohanBoer** [comment]
Dit heeft ook te maken met de vraag of je HAL toepast of niet. In geval van HAL zet je de link in een aparte _links sectie en neem je het identificerende veld zelf op in de resource. Dit heeft als voordeel dat een consumer als hij de identificatie locaal wil gebruiken / opslaan. Dat hij dan niet de identificatie uit het veld hoeft te peuteren.

**Comment by HenriKorver** [comment]
Het lijkt dat deze design rule strijdig is met de landelijke api strategie, zie https://publicatie.centrumvoorstandaarden.nl/api/adr/#api-06. Een ouder-kind resource relatie waar de kind resources alleen kunnen bestaan in de context van hun parent resource zijn altijd 1-n.

**Comment by HenriKorver** [comment]
In deze discussie zien we de uitleg waarom in het ZGW-project besloten is om de landelijke design rule API 06 niet toe te passen.

**Comment by HenriKorver** [comment]
> Dit heeft ook te maken met de vraag of je HAL toepast of niet. In geval van HAL zet je de link in een aparte _links sectie en neem je het identificerende veld zelf op in de resource. Dit heeft als voordeel dat een consumer als hij de identificatie locaal wil gebruiken / opslaan. Dat hij dan niet de identificatie uit het veld hoeft te peuteren.

Waarom zou je als je linkt naar een andere resource naast de url ook een id willen opnemen als referentie? Dat is toch redundantie...

**Comment by HenriKorver** [comment]
Voorbeeld:

```json
GET books/2
{
        "self": "/books/2",
        "id": 2,
        "title": "Title 2",
        "authors": ["/authors/3"]
}
```
is een stuk compacter dan

```json
GET books/2
{
        "self": "/books/2",
        "id": 2,
        "title": "Title 2",
        "authors": [
            { 
                "author": {
                    "id": 3,
                    "_links": {
                            "self": {
                                "href": "/authors/3"
                            }
                        }
                }
            } 
       ]
}
```

**Comment by JohanBoer** [comment]
Deze issue is afgedekt in de landelijk design rule API-06 . Daar conformeren wij ons aan, dus er komt op basis van deze discussie geen VNGR Design Rule. 
Als we in de praktijk een issue tegen komen die we niet kunnen afhandelen adhv API-06 wordt deze discussie opnieuw op de agenda gezet.
