### ISSUE TITLE
Bij namen van relaties (links naar gerelateerde resources) gebruiken we in principe de naam van de betreffende resource als propertynaam voor de link

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#36]
Wanneer de gerelateerde resource één keer kan voorkomen wordt de resourcenaam omgezet naar enkelvoud. Wanneer de relatie meerdere keren kan voorkomen, wordt de resourcenaam in meervoud gebruikt.      

Bij gebruik van de resourcenaam als propertynaam wordt lowerCamelCase toegepast (zie DD1.2).      

Wanneer de resourcenaam niet voldoende beschrijvend is voor de betekenis van de relatie ("adres" is "verblijfplaats" van een persoon), of wanneer de resourcenaam niet onderscheidend is (ouders, partners en kinderen zijn allen relaties naar ingeschrevenpersonen) kan gekozen worden om bijvoorbeeld de relatienaam te gebruiken, of bijvoorbeeld de relatienaam gevolgd door de resourcenaam. Zo nodig wordt dit ingekort of aangepast om tot een bondige en duidelijke naam te komen.      Bijvoorbeeld:   woonplaats (resource "woonplaatsen")   openbareRuimte (resource "openbareruimten")   verblijfplaats (resource "adressen")   kinderen (resource "ingeschrevenpersonen" en relatie "heeft kinderen")

**Comment by JohanBoer** [comment]
Oorsprong: https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/docs/design_decisions.md


Johan: Overnemen   Henri: Overnemen   Robert: Discussie   Michiel: Overnemen   Gershon: Bespreken   Jeanot: Idem DD1.6

Bij 0-n of 1-n relaties is deze buiten discussie .
Voor n-m relaties koppelen we de toepassing van deze design rule aan die discussie.

**Comment by melsk-r** [comment]
N.m.m. bestaat dit issue uit 3 Design Rules, elke alinea is er 1.

**Comment by JohanBoer** [comment]
Deze issue is opgedeeld in drie aparte design rule issues.
