### ISSUE TITLE
We gebruiken als enumeratiewaarden betekenisvolle waarden.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#42]
Dus niet M en V, maar man en vrouw.      

Ratio      Een developer moet bij het coderen begrijpen wat de code betekent, om fouten in de implementatie te voorkomen.      Kanttekening      De lengte van de enumeratiewaarden zal zoveel mogelijk beperkt moeten worden (Zie de design rule over lengtes van enumeratiewaarden #38).

**Comment by JohanBoer** [comment]
Johan: Overnemen   
Henri:   
Robert: Overnemen   
Michiel: Zie toelichting   
Gershon: Overnemen   
Jeanot: Side issue bespreken


Jeanot: Formulering 'zoveel mogelijk beperkt moeten worden' is wat sterk. DD2.6 staat niet in lijst.   

Michiel: Ik zou zeggen hou het consequent. Dus altijd Man/Vrouw ipv M/V maar M/V is op zich ook duidelijk genoeg (elke Nederlandstalige ontwikkelaar snapt het en een niet-Nederlandstalige ontwikkelaar weet ook niet wat Man/Vrouw betekent).   

Gershon: zie ook regel 62

**Comment by JohanBoer** [comment]
HK: Wil jij je advies hier toevoegen ?

**Comment by HenriKorver** [comment]
HK: Overnemen

**Comment by JohanBoer** [comment]
Deze opnemen in de design rules met als toelichting de verwijzing van Robert naar de API_kennisbank.
