### ISSUE TITLE
Gebruik bij bevraging-API's zo mogelijk een string i.p.v. een enumeration

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#44]
Noot: Onderstaande tekst aangepast n.a.v. opmerking RM :

Wanneer een gegeven in het informatiemodel gedefinieerd is als een enumeratie, maar de enumeratiewaarde wordt door gebruikers van de API alleen gebruikt om als tekst te tonen (bevraging-endpoints) aan eindgebruikers (mensen), definieer het gegeven dan als string (niet als enumeratie) in de API. 

Wanneer de enumeratiewaarde gebruikt wordt in code (algoritmes), definieer dan een betekenisvolle maar bondige code.      

Ratio : Het opnemen van een enumeratie in de API-definitie betekent dat voor het kunnen tonen van een nieuwe of gewijzigde waarde in de enumeratie een nieuwe versie van de API moet worden uitgebracht. Voor bevraging-API's is dat een ongewenste vorm van tight coupling
.
Als het gegeven echter wordt gebruikt in code (algoritme) dan is het van belang dat er niet afgeweken kan worden van de bekende waarden en is een definitie als enumeratie op zijn plaats.

**Comment by JohanBoer** [comment]
Johan: Overnemen
Henri:
Robert: Uitleg gewenst
Michiel: Overnemen
Gershon: Bespreken
Jeanot: Toelichting gewenst

**Comment by melsk-r** [comment]
Ik denk dat ik de tekst inmiddels begrijp.

Een gegeven kan in het informatiemodel als enumeratie zijn gedefinieerd. Als het gegeven echter alleen in de response op een bevraging voorkomt EN alleen wordt gebruikt om aan menselijke gebruikers te worden getoond dan is het niet nodig het ook in de API specificaties als een enumeratie te definiëren. Dat zou immers betekenen dat voor het kunnen tonen van een geheel nieuwe melding een nieuwe versie van de API moet worden uitgebracht. Een ongewenste vorm van tight coupling dus.
Als het gegeven echter wordt gebruikt in code (algoritme) dan is het van belang dat er niet afgeweken kan worden van de bekende waarden en is een definitie als enumeratie op zijn plaats.

Kan ik hieruit de conclusie trekken dat je ongewenste en gewenste vormen van tight coupling hebt?

Hoe zit het trouwens als datzelfde gegeven ook voorkomt in een post bericht. Volgens mij moet het dan weer wel als een enumeratie worden gedefinieerd. De ontvanger van dat bericht wil immers geen andere waarden ontvangen dan zijn toegestaan. Als dat klopt dan moet de zinsnede '... alleen in de response op een bevraging voorkomt ...' strikt worden geïnterpreteerd.

Ik stel voor om de beschrijving van deze Design Rule nog wat te verbeteren.

**Comment by JohanBoer** [comment]
> Ik stel voor om de beschrijving van deze Design Rule nog wat te verbeteren.

@mels-r (en ook anderen) Ik heb de concept-tekst en de ratio aangepast in de originele post. Als je het eens wil je dan je oordeel editen in het 2e comment ?

**Comment by melsk-r** [comment]
Ik heb het idee dat de tekst duidelijker kan. Een poging:

_Een gegeven kan in het informatiemodel gedefinieerd zijn als een enumeratie. Als het gegeven echter alleen in een response op een bevraging voorkomt EN alleen wordt gebruikt om aan menselijke gebruikers te worden getoond dan is het niet nodig het ook in de API specificaties als een enumeratie te definiëren. 

Wanneer de enumeratiewaarde gebruikt wordt in code (algoritmes), definieer dan een betekenisvolle maar bondige code.

Ratio : Het opnemen van een enumeratie in de API-definitie betekent dat voor het kunnen tonen van een nieuwe of gewijzigde waarde in de enumeratie een nieuwe versie van de API moet worden uitgebracht. Voor bevraging-API's is dat een ongewenste vorm van tight coupling.

Als het gegeven echter wordt gebruikt in code (algoritme) dan is het van belang dat er niet afgeweken kan worden van de bekende waarden en is een definitie als enumeratie op zijn plaats._

**Comment by JohanBoer** [comment]
Deze heeft een relatie met #42 en met #38 . 

We gaan in de design rules een voorstel opnemen hoe we omgaan met enumeraties / waardelijsten. 
Afhankelijk met het doel van de API en de afweging tussen enumeraties (risico op breaking changes) en waardelijsten (waardelijst moet dan in een API beschikbaar gemaakt worden) . 
Als er een omschrijving van de enumeratie waarde nodig is kan deze opgenomen worden in de description van de enumeraties. Eventueel kan in de component waar de enumeratie gebruikt wordt een "weergave-property" worden meegegeven. In die weergave-property wordt dan de uitgebreide omschrijving die bij de enumeratiewaarde hoort.  

In de design rule moeten de overwegingen opgesomd worden met voor / nadelen van elke oplossing.
