### ISSUE TITLE
Neem een indicator op als het gevuld zijn van een datum functionele betekenis heeft

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#54]
Wanneer het gevuld zijn van een datum functionele betekenis heeft, ook wanneer deze volledig onbekend is, wordt een indicator opgenomen om dit aan te geven. 

Indien in het onderstaande voorbeeld er helemaal niets bekend is van de overlijdensdatum, maar er is wel bekend dat de persoon overleden is, dan kan dat nergens uit worden afgeleid. Uit de reponse kan je niet opmaken of de overlijdensdatum leeg is omdat iemand  niet is overleden of omdat de overlijdensdatum niet bekend is.

```
    Persoon:
      type: object
      description: "Natuurlijkpersoon of NietNatuurlijkPersoon"
      properties:
        identificatie:
          type: string
        datumOverleden:  
          $ref: "#/components/schemas/TypePersoonEnum"type: string
        voorletters: 
          type: string
```

Door voor een dergelijke situatie een boolean op te nemen waar de betreffende informatie wordt gerepresenteerd wordt duidelijk wat de situatie is zonder dat er invalide waardes hoeven te worden opgenomen in de datum-velden.

```
    Persoon:
      type: object
      description: "Natuurlijkpersoon of NietNatuurlijkPersoon"
      properties:
        identificatie:
          type: string
        datumOverleden:  
          $ref: "#/components/schemas/TypePersoonEnum"type: string
        indicatieOverleden:
          type: boolean
        voorletters: 
          type: string
```

Ratio : Bijvoorbeeld of een persoon overleden is kan niet worden afgeleid uit het bestaan van een overlijdensdatum wanneer die datum onbekend is. Daarvoor kan een boolean "indicatieOverleden" worden gedefinieerd.

**Comment by JohanBoer** [comment]
JBo: Overnemen
HK:
RM: Overnemen, toelichting verbeteren
MV: Overnemen
GJ: Overnemen
JBi: Overnemen. Kan wel leiden tot conversie tussen bron en API.

**Comment by JohanBoer** [comment]
@HenriKorver : Wil jij je advies hierover toevoegen ?

**Comment by HenriKorver** [comment]
HK: Overnemen, maar toelichting verbeteren

Het zou helpen als de DR uitgelegd wordt aan de hand van concrete voorbeelden

**Comment by JohanBoer** [comment]
> Het zou helpen als de DR uitgelegd wordt aan de hand van concrete voorbeelden

Ben ik het mee eens Henri. Ik heb onderstaand voorbeeld toegevoegd aan de DR-tekst.


Indien in het onderstaande voorbeeld er helemaal niets bekend is van de overlijdensdatum, maar er is wel bekend dat de persoon overleden is, dan kan dat nergens uit worden afgeleid. Uit de reponse kan je niet opmaken of de overlijdensdatum leeg is omdat iemand  niet is overleden of omdat de overlijdensdatum niet bekend is.

```
    Persoon:
      type: object
      description: "Natuurlijkpersoon of NietNatuurlijkPersoon"
      properties:
        identificatie:
          type: string
        datumOverleden:  
          $ref: "#/components/schemas/TypePersoonEnum"type: string
        voorletters: 
          type: string
```

Door voor een dergelijke situatie een boolean op te nemen waar de betreffende informatie wordt gerepresenteerd wordt duidelijk wat de situatie is zonder dat er invalide waardes hoeven te worden opgenomen in de datum-velden.

```
    Persoon:
      type: object
      description: "Natuurlijkpersoon of NietNatuurlijkPersoon"
      properties:
        identificatie:
          type: string
        datumOverleden:  
          $ref: "#/components/schemas/TypePersoonEnum"type: string
        indicatieOverleden:
          type: boolean
        voorletters: 
          type: string
```

**Comment by JohanBoer** [comment]
In de toelichting komt te staan dat de datum velden geen ongeldige waarde (00000000) bevatten om aan te geven dat een datum onbekend is. Dit kan worden gecommuniceerd met een aparte property (in dit geval "indicatieOverleden".
