### ISSUE TITLE
Gebruik de 'allOf' constructie indien er meerdere componenten zijn met dezelfde properties

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/API-Kennisbank#58]
Wanneer er meerdere componenten zijn met meerdere dezelfde properties, moet er hergebruik worden gemaakt via een 'allOf' constructie. Dit sluit aan op object oriëntatie in de verschillende programmeeromgevingen.

Bijvoorbeeld een woonadres en een postadres zijn identiek, behalve dat postadres ook een postbusnummer kent. Dan is postadres een extensie op woonadres.
Bijvoorbeeld een natuurlijk persoon en een niet-natuurlijk persoon hebben beide een naam en een adres, maar beide hebben ook eigen gegevens (natuurlijk persoon heeft geboortedatum, niet-natuurlijk persoon heeft eigenaar), dan zijn beide een extensie op een bovenliggende component "Persoon".
Bijvoorbeeld bij een zakelijkGerechtigde worden alleen minimale identificerende gegevens van een persoon opgenomen (alleen naam en identificatie), maar bij de persoon (resource) worden meer eigenschappen van de persoon opgenomen (zoals adres). Dan gebruikt zakelijkGerechtigde het component "persoonBeperkt" en is de uitgebreide persoon een extensie hierop.

**Comment by JohanBoer** [comment]
JBo: Overnemen
HK:
RM: Overnemen
MV: Overnemen
GJ: Geen mening
JBi: Geen mening / Te weinig kenis

**Comment by JohanBoer** [comment]
@HenriKorver Zou jij hier je advies willen toevoegen ? Als dat van dezelfde strekking is als dat van RM, MV en mij kunnen we deze opnemen in de design rules.

**Comment by HenriKorver** [comment]
HK: Overnemen
