### ISSUE TITLE
Naamgeving pull request

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/API-Kennisbank#8]
De naam van een pull request moet voldoen aan de volgende conventie:

    fixit [nummer]

nummer is daarbij het nummer van het issue waar het pull request invulling aan geeft.

**Comment by sergei-maertens** [comment]
https://github.blog/2013-01-22-closing-issues-via-commit-messages/

Github ondersteunt zelf `close, closes, closed, fixes, fixed` & bij het mergen wordt het overeenkomstige issue dan automatisch gesloten. Zou het niet beter zijn om deze gewoon te gebruiken?

**Comment by melsk-r** [comment]
Je hebt helemaal gelijk. Ik sluit dit issue.
